### ISSUE TITLE
Loading modernizr.js returns 404

### ISSUE THREAD

**Issue by dehuszar** [sir-dunxalot/ember-cli-modernizr#1]
Hi there.  I'm attempting to get the add-on working, but after installation and configuration per the README I get a 404 on the library when ember-cli loads the site.

**Comment by sir-dunxalot** [comment]
Hey, what version of Ember CLI are you using? And if you look in your dist folder, do you see a modernizr file anywhere?

**Comment by dehuszar** [comment]
I'm using Ember-CLI 1.13.14.  Modernizr isn't making it into the dist folder.  The script tag that gets returned by `{{content-for 'body-footer'}}` points to "/assets/ember-cli-modernizr..js".

**Comment by sir-dunxalot** [comment]
Ok, I'm not immediately sure why it wouldn't write the file but I'll look into it.

I'm hoping to not even write the file but include the Modernizr build in `vendor.js` eventually.

**Comment by dehuszar** [comment]
Thanks!

**Comment by dehuszar** [comment]
Were able to confirm the issue on your end?  If there's anything you want me to try, let me know.

**Comment by sir-dunxalot** [comment]
I haven't been able to look into this yet, sorry.

**Comment by dehuszar** [comment]
That's okay.  I just did a mass-remove and scrubbing of all the options from ember-cli-build.js and reinstalled the addon and things began working.  So the initial problem was likely happening somewhere in my config.  I'll see if I can narrow it down, but I'll close this ticket for now.

**Comment by dehuszar** [comment]
Looks like the issue here is creating an options block.  As soon as I remove it from my ember-cli-build.js modernizr gets built and injected into the vendor.js file.  As soon as I try and set any options, I get the original 404 error stated above.

It would be nice to be able to set a prefix and limit tests to just what my project is using as, right now, I have to override classes like 'hidden' which erase the site's visibility.  But overall, not a deal breaker.

Here's an example of what I'm trying to set:

```
modernizr: {
    "classPrefix": "mdrnz-",
    "feature-detects": ["dom/hidden"],
    "shouldParseFiles": true
}
```

The only other config items I have are for PostCSS, and an app.import() of moment.  Uninstalling ember-cli-postcss and removing it's options from the config did not have any effect on the error.

**Comment by sir-dunxalot** [comment]
Thanks for digging into this some more. This should make it much easier to locate the core issue. This should be fixable and I will keep this thread updated with any progress.
