### ISSUE TITLE
HTML no longer rendered after installation

### ISSUE THREAD

**Issue by devilleweppenaar** [sir-dunxalot/ember-cli-modernizr#2]
I'm new to Ember and I'm using the 'The Project' Bootstrap template from WrapBootstrap. The template js uses Modernizr, and as soon as I add this addon (via 'ember install ember-cli-modernizr'), something seems to break.

I don't see any errors in the console, but the none of the HTML is rendered. This is resolved when I remove this addon.

I apologize in advance if I'm just being a noob. Any help would be greatly appreciated.

**Comment by sir-dunxalot** [comment]
No problem. I'm not sure how to dig into this without more info. Do you have a repo with this issue that you can share?

Perhaps 'The Project' is using Modernizr 2 instead of Modernizr 3?

**Comment by devilleweppenaar** [comment]
Thanks @sir-dunxalot! You hit the nail on the head. The template requires Modernizr 2.x instead 3.x, so I included the version that is provided with the template.

Thanks again for the suggestion!

**Comment by sir-dunxalot** [comment]
No problem, glad to help.

**Comment by dehuszar** [comment]
I am now also seeing this issue, but I am not using The Project, nor have I set up any template dependencies for Modernizr.
